---
- name: Check whether ssh cert for borg exists
  ansible.builtin.stat:
    path: "{{ playbook_dir }}/vaults/borg/.ssh/id_ed25519"
  register: ssh_config
  delegate_to: localhost

- name: Configure borgmatic and borg backups
  when:
    - ssh_config.stat.exists
    - borg_repository is defined
    - borg_encryption_passphrase is defined
    - borg_remote_path is defined
  block:
    - name: Sync local ssh config vault remote
      when: ssh_config.stat.exists
      become: true
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/vaults/borg/.ssh/"
        dest: "{{ ansible_user_home_dir }}/borgmatic/.ssh"
        mode: "0700"
        owner: root
        group: root

    - name: Render Borgmatic configuration
      become: true
      ansible.builtin.template:
        src: config.yaml.j2
        dest: "{{ ansible_user_home_dir }}/borgmatic/config.yaml"
        mode: "0600"
        owner: "{{ ansible_ssh_user }}"

    - name: Pull borgmatic image
      become: true
      community.docker.docker_image:
        name: ghcr.io/borgmatic-collective/borgmatic:2
        source: pull
        state: present

    - name: Create borg repository if it does not exist
      community.docker.docker_container:
        image: ghcr.io/borgmatic-collective/borgmatic:2
        name: datalab-borgmatic
        volumes:
          - "{{ ansible_user_home_dir }}/borgmatic/config.yaml:/etc/borgmatic.d/config.yaml"
          - "{{ ansible_user_home_dir }}/borgmatic/.ssh:/root/.ssh"
          - /data:/data
        command: borgmatic init --encryption=repokey
        auto_remove: true

    - name: Add Cron job for borgmatic
      ansible.builtin.cron:
        name: borgmatic
        hour: "2"
        minute: "{{ range(0, 59) | random(seed=inventory_hostname) }}"
        user: "{{ ansible_user }}"
        job: timeout 6h docker run --rm --network datalab_backend --name datalab-borgmatic -v {{ ansible_user_home_dir }}/borgmatic/config.yaml:/etc/borgmatic.d/config.yaml -v {{ ansible_user_home_dir }}/borgmatic/.ssh:/root/.ssh -v /data:/data ghcr.io/borgmatic-collective/borgmatic:2 borgmatic -v 1 # noqa: line-length
