---
- name: Create a Docker volume for certbot-conf (mounted to /etc/letsencrypt)
  community.docker.docker_volume:
    name: certbot-conf

- name: Create a Docker volume for certbot-www (mounted to /var/www/certbot)
  community.docker.docker_volume:
    name: certbot-www

- name: Build/pull certbot image
  community.docker.docker_image:
    name: certbot/certbot:latest
    source: pull
    state: present
    force_source: true

- name: Synchronize nginx files to remote
  ansible.posix.synchronize:
    src: "{{ role_path }}/files/"
    dest: "{{ ansible_user_home_dir }}/nginx"

- name: Render templated certbot config
  ansible.builtin.template:
    src: certbot-docker.sh.j2
    dest: "{{ ansible_user_home_dir }}/nginx/rendered/certbot-docker.sh"
    mode: "0744"

- name: Build nginx image
  community.docker.docker_image:
    name: datalab-nginx
    source: build
    state: present
    force_source: true
    build:
      path: "{{ ansible_user_home_dir }}/nginx"

- name: Launch nginx container without services
  community.docker.docker_container:
    name: datalab-nginx
    image: datalab-nginx
    network_mode: host
    volumes:
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    restart_policy: false

- name: Launch certbot container
  community.docker.docker_container:
    name: datalab-certbot
    image: certbot/certbot:latest
    network_mode: host
    volumes:
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
      - "{{ ansible_user_home_dir }}/nginx/rendered/certbot-docker.sh:/opt/certbot-docker.sh"
    restart_policy: false
    detach: true
    entrypoint:
      - /opt/certbot-docker.sh

- name: Scheduled SSL renewal with certbot
  ansible.builtin.cron:
    name: SSL renewal with certbot
    minute: "38"
    hour: "10"
    day: "2"
    month: "*"
    job: docker run -v certbot-www:/var/www/certbot -v certbot-conf:/etc/letsencrypt certbot/certbot:latest renew
