---
- name: Mount data disk (if requested)
  become: true
  when: mount_data_disk is defined and mount_data_disk != ''
  ansible.posix.mount:
    path: /data
    src: "{{ mount_data_disk | default('') }}"
    fstype: "{{ data_disk_type | default('xfs') }}"
    state: mounted

- name: Install aptitude
  become: true
  ansible.builtin.apt:
    name: aptitude
    state: present
    update_cache: true

- name: Install required system packages
  become: true
  ansible.builtin.apt:
    pkg:
      - ca-certificates
      - python3-pip
    state: present
    update_cache: true
