#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = ["pyyaml"]
# ///
"""Generate the role reference pages from the roles' argument specs.

Each role in ansible/roles declares its variables in meta/argument_specs.yml.
This script renders one page per role into docs/reference, plus an index, so
that the documentation cannot drift from the specs the playbook validates
against. The pages are generated by `make docs` and are not committed.
"""

import pathlib
import shutil
import sys
import tomllib

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
ROLES = ROOT / "ansible" / "roles"
PLAYBOOK = ROOT / "ansible" / "playbook.yml"
CONFIG = ROOT / "zensical.toml"
OUT = ROOT / "docs" / "reference"


def nav_roles() -> list[str]:
    """The roles listed under Reference in the nav, which is the source of truth."""
    nav = tomllib.loads(CONFIG.read_text())["project"]["nav"]
    for entry in nav:
        for title, value in entry.items():
            if title == "Reference":
                return [
                    pathlib.Path(page).stem
                    for child in value
                    for page in child.values()
                    if pathlib.Path(page).stem != "index"
                ]
    return []


def check_nav(found: list[str]) -> None:
    """Fail if a role was added or removed without updating the nav."""
    listed = nav_roles()
    missing = [r for r in found if r not in listed]
    extra = [r for r in listed if r not in found]
    if not missing and not extra:
        return
    if missing:
        print(f"Roles missing from the Reference nav in zensical.toml: {', '.join(missing)}")
    if extra:
        print(f"Roles in the Reference nav with no argument spec: {', '.join(extra)}")
    sys.exit(1)


def role_tags() -> dict[str, list[str]]:
    """Map each role to the tags it can be run with, as used by `make <tag>`."""
    tags: dict[str, list[str]] = {}
    for play in yaml.safe_load(PLAYBOOK.read_text()) or []:
        for role in play.get("roles") or []:
            if isinstance(role, dict) and "role" in role:
                tags.setdefault(role["role"], []).extend(role.get("tags") or [])
    return tags


def defaults(role: pathlib.Path) -> dict:
    path = role / "defaults" / "main.yml"
    if not path.exists():
        return {}
    return yaml.safe_load(path.read_text()) or {}


def as_text(value) -> str:
    """Render a description, which may be a string or a list of paragraphs."""
    if isinstance(value, list):
        return " ".join(str(v).strip() for v in value)
    return str(value or "").strip()


def as_code(value) -> str:
    if value == "":
        return ""
    if isinstance(value, bool):
        return f"`{str(value).lower()}`"
    if isinstance(value, (list, dict)):
        return f"`{yaml.safe_dump(value, default_flow_style=True).strip()}`"
    return f"`{value}`"


def option_rows(options: dict, role_defaults: dict) -> list[str]:
    rows = []
    for name, spec in options.items():
        spec = spec or {}
        default = spec.get("default", role_defaults.get(name))
        cells = [
            f"`{name}`",
            f"`{spec.get('type', 'str')}`",
            "yes" if spec.get("required") else "no",
            as_code(default) if default is not None else "",
            as_text(spec.get("description")),
        ]
        if spec.get("choices"):
            cells[-1] += " One of: " + ", ".join(as_code(c) for c in spec["choices"]) + "."
        rows.append("| " + " | ".join(cell.replace("|", r"\|") for cell in cells) + " |")
    return rows


def render(name: str, spec: dict, role_defaults: dict, tags: list[str]) -> str:
    entry = spec.get("main") or next(iter(spec.values()), {})
    lines = ["---", f"title: {name}", "---", "", f"# `{name}`", ""]
    if entry.get("short_description"):
        lines += [f"{entry['short_description']}.", ""]
    for paragraph in entry.get("description") or []:
        lines += [as_text(paragraph), ""]
    if tags:
        joined = ", ".join(f"`{t}`" for t in dict.fromkeys(tags))
        lines += [f"Tags: {joined}", "", f"Run it on its own with `make {list(dict.fromkeys(tags))[-1]}`.", ""]
    options = entry.get("options") or {}
    if options:
        lines += [
            "## Variables",
            "",
            "Set these per host in `ansible/inventory.yml`.",
            "",
            "| Variable | Type | Required | Default | Description |",
            "| --- | --- | --- | --- | --- |",
            *option_rows(options, role_defaults),
            "",
        ]
    else:
        lines += ["This role takes no configuration.", ""]
    return "\n".join(lines)


def main() -> None:
    specs = sorted(
        role for role in ROLES.iterdir() if (role / "meta" / "argument_specs.yml").exists()
    )
    check_nav([role.name for role in specs])
    tags = role_tags()
    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir(parents=True)

    index = [
        "---",
        "title: Role reference",
        "---",
        "",
        "# Role reference",
        "",
        "Every role declares the variables it accepts in its own `meta/argument_specs.yml`.",
        "Ansible validates the inventory against those specs when the playbook runs, and these pages are generated from them, so they cannot drift apart.",
        "",
        "See [Configuration](../configuration.md) for the settings most deployments need.",
        "Each role also has its own page, listed under Reference in the sidebar.",
        "",
        "| Role | Tags | Description |",
        "| --- | --- | --- |",
    ]

    for role in specs:
        spec_path = role / "meta" / "argument_specs.yml"
        spec = (yaml.safe_load(spec_path.read_text()) or {}).get("argument_specs", {})
        entry = spec.get("main") or next(iter(spec.values()), {})
        role_tags_ = list(dict.fromkeys(tags.get(role.name, [])))
        (OUT / f"{role.name}.md").write_text(render(role.name, spec, defaults(role), role_tags_))
        index.append(
            "| [`%s`](%s.md) | %s | %s |"
            % (
                role.name,
                role.name,
                ", ".join(f"`{t}`" for t in role_tags_) or "",
                entry.get("short_description", ""),
            )
        )

    (OUT / "index.md").write_text("\n".join(index) + "\n")
    print(f"Wrote {len(list(OUT.glob('*.md')))} pages to {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
